export enum ErrorCode {
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    PASSWORD_MUST_CONTAIN_LETTER_AND_NUMBER = 'PASSWORD_MUST_CONTAIN_LETTER_AND_NUMBER',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    FAILED_TO_DESERIALIZE_USER = 'FAILED_TO_DESERIALIZE_USER',
    FORBIDDEN = 'FORBIDDEN',
}
