export enum ErrorCode {
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    PASSWORD_MUST_CONTAIN_LETTER_AND_NUMBER = 'PASSWORD_MUST_CONTAIN_LETTER_AND_NUMBER',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    FAILED_TO_DESERIALIZE_USER = 'FAILED_TO_DESERIALIZE_USER',
    FORBIDDEN = 'FORBIDDEN',
    THIS_FIELD_IS_REQUIRED = 'THIS_FIELD_IS_REQUIRED',
    MUST_BE_STRING = 'MUST_BE_STRING',
    MUST_BE_AT_LEAST_1_CHARACTERS = 'MUST_BE_AT_LEAST_1_CHARACTERS',
    MUST_BE_AT_MOST_255_CHARACTERS = 'MUST_BE_AT_MOST_255_CHARACTERS',
    CAFE_NOT_FOUND = 'CAFE_NOT_FOUND',
    BUSINESS_NAME_ALREADY_EXISTS = 'BUSINESS_NAME_ALREADY_EXISTS',
}
